<a href="https://colab.research.google.com/github/Rixxi21/NumPy-Array/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

In [ ]:
lista =[1, 2, 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]

1

In [ ]:
arr[5] + arr[3]

10

In [ ]:
matriz 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0,2]

3

In [ ]:
arr 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:8]

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr[5:8]

array([6, 7, 8])

In [ ]:
arr[::2]

array([1, 3, 5, 7, 9])

In [ ]:
arr[-1]

9

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
matriz2 = ([[[1,2,3],[4,5,6],[7,8,9]],
            [[10,11,12,],[13,14,15],[16,17,18]]])
matriz2 = np.array(matriz2)
matriz2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
matriz2.ndim

3

In [ ]:
matriz2[0:4, 4:6, 2:5]

array([], shape=(2, 0, 1), dtype=int64)